Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.provision "shell", inline: <<-SHELL
    version=2.6.0
    sudo apt-get update
    sudo apt-get install -y build-essential autoconf libtool libarchive-dev
    curl -LO https://github.com/singularityware/singularity/releases/download/${version}/singularity-${version}.tar.gz
    tar -zxf singularity-${version}.tar.gz
    cd singularity-${version}
    ./autogen.sh
    ./configure --prefix=/usr/local
    make
    sudo make install
    cd ..
    rm -fr singularity-${version}.tar.gz singularity-${version}
  SHELL
end
