Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provision "shell", inline: "yum -y install boost-python"
  config.vm.provision "shell", path: "dirac_install.sh", privileged: false
  config.vm.provision "file", source: "~/.globus", destination: "$HOME/.globus"
end
